### ISSUE TITLE
Sort changing Rows Per Page to default

### ISSUE THREAD

**Issue by rmondc** [MicroDroid/vue-materialize-datatable#44]
My default row per page is 10. But when I set it to a 100 and sort by clicking the column header, it returned to my default row per page of 10, instead of showing the 100 rows.

Why does this.currentPerPage go back to default after sort?

```
sort: function(index) {
      if (!this.sortable) return;
      if (this.sortColumn === index) {
        this.sortType = this.sortType === "asc" ? "desc" : "asc";
      } else {
        this.sortType = "asc";
        this.sortColumn = index;
      }
    },
```
Looks like its from 
```
computed: {
...
        this.currentPerPage = options[0];
...
}
```
I change the above to this.currentPerPage = this.currentPerPage as a work around but not sure what will it affect.

**Comment by rmondc** [comment]
> My default row per page is 10. But when I set it to a 100 and sort by clicking the column header, it returned to my default row per page of 10.
> 
> Why does this.currentPerPage go back to default after sort?
> 
> sort: function(index) {
> if (!this.sortable) return;
> if (this.sortColumn === index) {
> this.sortType = this.sortType === "asc" ? "desc" : "asc";
> } else {
> this.sortType = "asc";
> this.sortColumn = index;
> }
> },

**Comment by MicroDroid** [comment]
I couldn't reproduce this issue. However, I suspect it happens because your `per-page` options are changing right after sorting for some reason, causing resetting `this.currentPerPage` internally as you mentioned.

While I have removed that piece of code and replaced it with a `watch`er, it may still occur for you if you have some issues in your own code.
